### ISSUE TITLE
Update to Audiolats

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/public-website#1]
Here some modifications for the CD web site.
AUDIOLATS
- the subtitle is :
Leonardo/Olats sound bites series
La collection de publications sonores de Leonardo/Olats

- in the introductory blurb in English, could you change "Introducting..." by "Meeting ..."

- French description
It would be nice if you could add the French description. I think it is important both for CD and for Olats.
Here it is.

Audiolats est la chaîne de publication audio de Leonardo/Olats, la branche française de Leonardo/Isast.  À la croisée de la publication et de la création sonores, elle propose trois formats : "Rencontre avec ...", où une personnalité présente ses idées et recherches ; "Il était une fois une œuvre ....", où une personnalité parle d'une œuvre qu'il ou elle considère comme marquante dans le domaine art, science, technologie ; "Et ça veut dire ?", où une personnalité donne sa définition d'une notion, d'un concept ou d'un champ de recherches.

SPACE ART AND CULTURE

Here, too, it would be nice if you could add the description of the chanel in French. Here it is :

En 1957, Spoutnik marquait de son bip bip les débuts de l'ére spatiale. Pour les artistes ce fut aussi l'ouverture d'un nouveau territoire pour la création. Leonardo a accompagné ces artistes en publiant les articles sur leurs œuvres, puis en lançant le "Leonardo Space and the Arts Project" conduit par Leonardo/Olats. "Art & Culture Spatiales" poursuit les investigations.

**Comment by cassininazir** [comment]
Josephine, noticed that you self-assigned this task. Feel free to assign to a member of the dev team.

**Comment by porteriffic** [comment]
Cassini,
For some reason I can't see any of the dev team when click on "Assignee".

**Comment by cassininazir** [comment]
Haven't heard back from them as yet. Need their Git usernames.

Sent from my iPhone

On Feb 13, 2015, at 4:58 PM, porteriffic <notifications@github.com<mailto:notifications@github.com>> wrote:


Cassini,
For some reason I can't see any of the dev team when click on "Assignee".

�

**Comment by cassininazir** [comment]
This appears to have been taken care of.
