### ISSUE TITLE
Voices names on disturbances web page

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#100]
@creativedisturbance/developers @creativedisturbance/design 
Is there any way to have the names of the voices shown within the disturbance pages ? not within the podcast page, which is already the case but for example here 
http://creativedisturbance.org/channel/virtual-africa/ 
it seems that people have interest in a podcast (not only because of that but also) according to the reputation/notoriety of the featured voice so it is important to know who is in the podcast before clicking the podcast link
would be nice to have voices names either underneath the title or on the right side of the screen..

thanks

**Comment by cassininazir** [comment]
This is a good idea. @anvit assigning to you for implementation.

**Comment by yvantina** [comment]
@cassininazir thank you !

**Comment by cassininazir** [comment]
@yvantina we implemented this for the individual podcasts (see http://creativedisturbance.org/podcast/mapping-the-space-low-tech-for-local-relevances/). @anvit can you take a look at the code Sruthi wrote and also implement for the channel listing page.

**Comment by yvantina** [comment]
@cassininazir @anvit @sayloo thanks guys ! :)
