### ISSUE TITLE
Weird font for Robertina Šebjanič 

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/public-website#103]
The 'S' and 'C' in Robertina's last name are a different font than the rest of the name. Don't know if this can be fixed or not.

**Comment by cassininazir** [comment]
This appears to be fixed. @porteriffic could you take a screenshot and post? I can't seem to duplicate on my computer.

**Comment by anvit** [comment]
I couldn't recreate it on my system either. But seems to be an OS specific font issue. I have this problem on the lab system but not on my laptop. Trying to narrow down the reasons since I think we're using a web font so the OS not having a font shouldn't be an issue.

**Comment by cassininazir** [comment]
Take a screenshot and attach here.
________________________________

**Comment by porteriffic** [comment]
![screenshot 17](https://cloud.githubusercontent.com/assets/10836612/7529195/30dc41b8-f4fa-11e4-8a7a-77b770aac67d.png)

**Comment by cassininazir** [comment]
Closing this. Reopen if needed.
