### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#104]
the audiolats image doesnt link to the audiolats channel so there is no way for a viweer to click though and see the other audiolats podcasts

http://creativedisturbance.org/podcast/performing-with-jellyfishes-meeting-with-robertina-sebjanic/

does the check list indicate checking that all the linls work before posting ?

roger

**Comment by cassininazir** [comment]
@anvit can you also investigate this?

**Comment by porteriffic** [comment]
@cassininazir @rmalina I'm not sure I understand what the problem is. Every time I click the Audiolats image I'm taken to the channel and the podcasts.

**Comment by cassininazir** [comment]
This appears to have been fixed.
