### ISSUE TITLE
recent pocasts page not updated

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#106]
corey

the recent podcasts page has not been updated with the podcast
that went up this morning- doesnt the cheat sheet have us checking this ]?

roger

**Comment by rmalina** [comment]
corey- at monday;s meeting an you all review in DETAIL the check list/cheat sheet that must be completed when a podcast goes up ? i dont understand how these kinds of glitches are occuring if your check list is complete and each of you actually uses the check list
roger

**Comment by rmalina** [comment]
i just checked- the cinemersia channel also doesnt have the gaucher podcast that i listened to as the new podcast this morning on stitcher- so both the recent podcasts page and the channel page didnt get updated when the new podcast went up
roger

**Comment by porteriffic** [comment]
Roger, someone must have already fixed this. I'm going to go ahead and close this issue. If you're still not seeing the correction, you can reopen the issue.
