### ISSUE TITLE
Change update process for 'featured voices'

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#107]
the 'featured voices' list is not getting up dated at the same time as the featured pocasts
is getting updated

suggest you modifiy process so that the featured voics are automatically updated with the featured podcasts and are those voices

roger

**Comment by porteriffic** [comment]
Voices must be updated manually. Will work with dev team to make it so that it is updated automatically.

**Comment by cassininazir** [comment]
@anvit am assigning this to you.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#172
