### ISSUE TITLE
Prep Languages for Polyglot Day

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#110]
*Close if this is a duplicate. Cant' remember if we tracked this somewhere.*

Please get new languages ready for Polyglot Day. It looks like we may have (@porteriffic please edit this issue to add any languages that we are missing): 

- German
- Bengali
- Korean
- Bahasa
- Japanese
- Spanish
- Russian
- Swedish (?)

Parameters: 

- New languages should appear in the drop-down list in main navigation bar. Please prep this. 
- Figure out the answer to this question: How much content of the website should be in that new language? And who should write?
- Review website for anything additional.

**Comment by porteriffic** [comment]
Still working on coordinating the podcast in Russian. All the other ones are set in motion as far as I know.

The Swedish podcast is highly unlikely, but I'll still try to get one.

**Comment by anvit** [comment]
I've prepped all the languages on the production server and I'm set to move it to the live one as soon as we're ready. 
I have a question about Bahasa though. I see two kinds: Bahasa Melayu(Malay) and Bahasa Indonesia(Indonesian). Which language is the podcast going to be in?

**Comment by porteriffic** [comment]
@anvit I'm 99.9% sure it's Bahasa Indonesia. Susan Eriksson said that's where her guest is from.

**Comment by anvit** [comment]
The languages are all set! @cassininazir Should I wait till Polyglot day to enable those or do you want to enable them immediately.
