### ISSUE TITLE
Synthetic Biology: Creating or Constructing Life ?

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#111]
@halclark Hey Hal ! is there anyway to change the title as indicated above for Poe and Roosth's podcast ? it makes more sense to me this way.. Thank you !

**Comment by halclark** [comment]
Sure, will do once I get back to my computer

**Comment by yvantina** [comment]
@halclark  Cool..

**Comment by halclark** [comment]
Changed the podcast name to "Synthetic Biology: Creating or Constructing Life?". Due to the context, I assumed that you also wanted the question mark included. Is this correct?

**Comment by yvantina** [comment]
@halclark yes thanks
