### ISSUE TITLE
Low-Tech for Local Relevance

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#114]
@amb141330 Hey Ashton, can you please update the podcast with Marcus Neustetter as indicated above ? it makes more sense to me this way - much thanks
http://creativedisturbance.org/podcast/mapping-the-space-low-tech-for-local-relevances/

**Comment by amb141330** [comment]
Done.

**Comment by yvantina** [comment]
@amb141330 Danke !
