### ISSUE TITLE
Gilles Kounou podcasts 

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#115]
@amb141330 @coreysmart92 
Ashton, Corey this podcast is the second part of my conversation with G.Kounou
http://creativedisturbance.org/podcast/ontologies-vocales-et-technologies-endogenes/
I've indicated 1/2 and 2/2 on the podcast description forms - so it should have 2/2 after the title and come with the right description.. 
please change accordingly and replace this podcast with the other one = the first part !!
thanks

**Comment by coreysmart92** [comment]
@amb141330 @yvantina I have updated both Libsyn and Wordpress, please check (Creative Disturbance) [http://creativedisturbance.org/podcast/ontologies-vocales-et-technologies-endogenes/]and let me know if it is still not correct.
