### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/public-website#117]
The site looks a little out of date. Here are some things I noticed:

- There are currently 10 podcasts on the channel instead of 9.
- 100th podcast banner is still on the home page.
- Voices are out of date.

@kkondas Was this discussed at Monday's meeting?

**Comment by rmalina** [comment]
good points ! now that sruthi is gone i suspect we need to review job descriptions to make sure we know who is responsible for the web site updating !
roger

**Comment by porteriffic** [comment]
@rmalina This is something that's supposed to be checked during the Monday meetings (I wasn't there this past Monday). Also, we've discussed Sruthi's responsibilities before she left and this was not one of them. All of her tasks have been transferred to Anvit.

**Comment by rmalina** [comment]
its really getting ridiculous that our 100th podcast banner has been ip for a month
can i suggest that the monthly banner only be up for a week ?

roger

**Comment by heiwanalady** [comment]
@rmalina @porteriffic @amb141330 @cassininazir 
Went ahead and took the banner down.

**Comment by cassininazir** [comment]
Home page has been updated. Closing this task.
