### ISSUE TITLE
Update Virtual Africa Producers

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#119]
Welcoming Marcus Neustetter on board ! @cassininazir @porteriffic @ChazLilly  @anvit  Do you mind updating this page http://creativedisturbance.org/channel/virtual-africa/  this way as Marcus is co-producing the channel with me now ?  "Hosted by Marcus Neustetter and Yvan Tina"
Please remove Roger's and Annick's name. Thank you !

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#168
