### ISSUE TITLE
Spelling Mistake - Please correct this title !!!

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#120]
http://creativedisturbance.org/podcast/jacques-mandelbrojt-se-rappel-a-voix-haute/
Please update the title into >> "Jacques Mandelbrojt se rappelle à voix haute"
@halclark @coreysmart92 @amb141330

**Comment by yvantina** [comment]
Please update also the description of the podcast into >>

" Jacques Mandelbrojt est physicien à la retraite de l'Université d'Aix-Marseille mais a eu durant toute sa carrière une vie d’artiste professionel. Il explique sa decouverte personnelle des ressemblances du processus créatif en art et en science. Il relie ainsi les idées de Piaget et de Cézanne qui parlait de “ce que les yeux pensent" alors que Piaget évoque des analogies entre pensée et vision qui lui semblent inséparables. Il cite encore Cézanne qui parlait "d'unir les formes des femmes aux épaules des collines“. Il discute enfin de sa pratique qui se situe entre création visuelle et création artistique"

**Comment by yvantina** [comment]
Please update also Jacques Mandelbrojt into >>

"Jacques Mandelbrojt est un artiste et physicien theorique. Il peint depuis 1942 et a participé à de nombreuses expositions artistiques et publié de nombreux articles scientifiques. Il a été professeur é l'Université de Marseille. Sa carriere hybride l’a notamment mené à explorer les processus créatifs en art et en science. Il est éditeur honoraire de la revue Leonardo depuis 1970."

**Comment by halclark** [comment]
Fixed

2015-07-08 11:23 GMT-05:00 yvantina <notifications@github.com>:

**Comment by yvantina** [comment]
Not fixed on Home page !

**Comment by halclark** [comment]
Check again, it is updated for me?

- Hal

**Comment by yvantina** [comment]
Okay cool ! it works for me as well
thanks

2015-07-08 18:23 GMT-05:00 halclark <notifications@github.com>:

> Check again, it is updated for me?
>
> - Hal
>
> On 7/8/15, yvantina <notifications@github.com> wrote:
> > Not fixed on Home page !
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/creativedisturbance/public-website/issues/120#issuecomment-119751454
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/public-website/issues/120#issuecomment-119757577>
> .
>



-- 
check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/
