### ISSUE TITLE
Spelling Mistake - Please correct this description

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#121]
@coreysmart92 @halclark @amb141330 @porteriffic 
http://creativedisturbance.org/podcast/jacques-mandelbrojt-lecons-de-liberte-fr/
Please update the current description into >>
"Jacques Mandelbrojt est physicien à la retraite de l’Université d’Aix-Marseille mais a eu durant toute sa carrière une vie d’artiste professionel. Le podcast commence avec l’idée de Jacques Monod selon laquelle le processus de travail et de pensée n’est pas tant verbal que visuel et musculaire, lui qui disait parfois s’identifier à une molécule. Mandelbrojt revient sur son parcours dans les arts et les sciences en tant que physicien, lequel inclue notamment la création du département d’art de l'Université de Marseille dans les années 70. Il se confie aussi sur les difficultés de la mise en oeuvre d’une formation en arts et sciences qui ne datent pas d'aujourd'hui et des obstacles rencontrés un demi-siècle plus tôt. Entretien avec Roger Malina"

**Comment by halclark** [comment]
Fixed
