### ISSUE TITLE
Update WordPress to 4.1

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#21]
_From @cassininazir on February 2, 2015 17:59_

Investigate what the fallout is of updating. 

_Copied from original issue: cassininazir/creativedisturbance#81_

**Comment by cassininazir** [comment]
_From @anvit on February 2, 2015 18:5_

Issues with updating 'WPBakery Visual Composer' and 'WPMU DEV Dashboard'. Manual update required because of API key error.

**Comment by cassininazir** [comment]
Theme plugin giving trouble. 

- Will need Envato username and API key. 
- Will need to duplicate live info on production server.

**Comment by anvit** [comment]
Production server is up at: http://production.cd2.texashats.org/ running Wordpress 4.1.1. The home page might display a default Wordpress page due to the cache but once logged in, all URLs work correctly.

**Comment by cassininazir** [comment]
Yeah!

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas
