### ISSUE TITLE
Create album artwork for Cellphonia

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#26]
_From @cassininazir on January 30, 2015 18:31_

Cellphonia (the cellphone opera channel)

Producer Steve Bull and myself have spent the last decade producing a variety of new forms of "opera" that are linked to cellphone use and the general concept of "opera". We have a collection of results from this work that we would post as "podcasts". Additionally, we plan to supplement these extant mp3s with interviews and reactions from our various contributors.

cellphone, opera, new media, sound art, interactivity

http://cellphonia.org

Scot Gresham-Lancaster

Add'l info:
Much of the "entertainment" aspect of this channel is already "in the can" as it represents a decade of various works. The production will be involved with the associated interviews and, of course the new cellphonia operas that are being produced just about annually.

_Copied from original issue: cassininazir/creativedisturbance#69_

**Comment by heiwanalady** [comment]
This is done, by the way. It's been uploaded into the Album Artwork folder in the Gdrive for a week or so.
