### ISSUE TITLE
Dropbox Storage

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#27]
_From @porteriffic on February 24, 2015 20:10_

Creative Disturbance shared Dropbox is taking up "free" space on other's Dropbox accounts.

_Copied from original issue: cassininazir/creativedisturbance#114_

**Comment by cassininazir** [comment]
@porteriffic Did we solve this one? Closing this issue. Re-open and comment if we haven't.

**Comment by porteriffic** [comment]
Not really. We've all agreed to take podcasts off the Dropbox once we are done with them and archive them into the servers at school. We can discuss tomorrow.
