### ISSUE TITLE
Update the Meet the Team Page with New Photos

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#49]
_From @cassininazir on January 30, 2015 22:26_

_Copied from original issue: cassininazir/creativedisturbance#75_

**Comment by cassininazir** [comment]
_From @heiwanalady on February 9, 2015 17:36_

Will need short descriptions of the new sound team!

**Comment by cassininazir** [comment]
_From @porteriffic on February 23, 2015 19:14_

Hal and Corey posted theirs in GitHub.

**Comment by vivraman** [comment]
This should be done unless I missed something?

@cassininazir confirm?

**Comment by vivraman** [comment]
Is this complete?
