### ISSUE TITLE
Usage Patterns

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#50]
_From @cassininazir on January 30, 2015 19:57_

- People who come to the website to listen on mobile devices (home page has to scroll a great deal)
- Title and descriptions of Non-English podcasts should be written in the language podcast was written in

_Copied from original issue: cassininazir/creativedisturbance#73_

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#187
