### ISSUE TITLE
Enable custom meta descriptions for each channel and podcast

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#52]
This will help immensely with SEO. Use the < meta name="description" content=" " > for 

- **Channels** should be the unique description 
- **Podcasts** should be the unique podcast description. If unavailable, use the channel description.

**Comment by cassininazir** [comment]
Of related interest #58.

**Comment by cassininazir** [comment]
This has been fixed with the Facebook Poster.

**Comment by anvit** [comment]
Completed!
