### ISSUE TITLE
Community Building via Buddypress

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#53]
BuddyPress plugin has been installed on the production server. http://buddypress.com

This task is to 

1. Get Buddypress working! 
2. Move current users from WP Members to BuddyPress
3. Create interactions among community members

**Comment by cassininazir** [comment]
This would also include:

1. Registration - New members would register through BuddyPress
2. Confirmation Screen - What page comes up after someone creates an account? 
3. Emails - What email(s) get pushed after account creation?

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#186
