### ISSUE TITLE
International Women's Day Podcast Page

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#54]
Podcasts to be included: 
 
1. Birds of Change with Nil Arsala *(Bold Roast)* - Published 3/6
2. Margaret Schdele *(Sound Data)* - Already published
3. **Roots of Curiosity Conference with Patricia Correia** *(Bold Roast)*  - Portuguese, EN - Publish 3/8
4. Paulina Oliveros *(Sound Data)* - Publish 3/8
5. **Personalized Learning Using Modeling** *(Voices of the Crowd)* - Publish 3/8
5. Dark Matter in Astronomy and in Art *Voices from the Crowd*
6. Using Big Data to Make Big - and Little - Decisions *Big Dreams, Big Data*
7. Why Big Dreamers Need to Know About Big Data *Big Dreams, Big Data*
8. Introduction to Art and Earth Science *Art and Earth Science* 
9. La culture des données (Art-Science : Emergences et ruptures) *Audiolats* - FR
10. The Intertwining Constructions of Blackness *The Bold Roast* 
11. Cancer Finding Beauty in the Beast *The Bold Roast*
12. Lets Play: Curating Video Game Criticism: *Indie Game Nation* Lindsey Joyce  

May be included:

- Charissa and Carroll
- Florian Glond 
- Jillian Round: Uploaded on 3/7

**Comment by cassininazir** [comment]
Changes to the following pages. 

Home Page 
- Banner or graphic: Creative Disturbance Celebrates International Women's Day, March 8
- Featured Voices - Should be voices from current podcasts 

International Women's Day
- Boiler plate content introducing the day
- Podcasts 

Social Media 
- Use #iwd #womensday #iwd2015

**Comment by cassininazir** [comment]
@porteriffic page is in production at www.creativedisturbance.org/womensday (must be logged in to view).

**Comment by porteriffic** [comment]
Will work on email and send out by tomorrow.

**Comment by heiwanalady** [comment]
![iwd_graphic](https://cloud.githubusercontent.com/assets/6133439/6536787/2032921e-c416-11e4-9012-8bace7f56ced.jpg)
The graphic that will spotlight the homepage - will still need link to the splash page.

**Comment by porteriffic** [comment]
Email sent out on 3/6.
