### ISSUE TITLE
Draft pages for "Voices" and "New Post"

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/public-website#55]
Not sure if this is just happening to me, but each time I scroll to the bottom of the page when posting a "Voice" or a "New Post", I am not able to scroll back up. This has happened each time I do this. Is this just my stupid computer? I don't have any page scrolling issues on any other site. Just on WordPress stuff. Is anyone else having this issue?

**Comment by vivraman** [comment]
it only happens when you update the picture specifically, accessing the
media section while editing a voice or podcast or channel causes it to
disappear

**Comment by vivraman** [comment]
in other news Nah its not just you

**Comment by porteriffic** [comment]
Gotcha! Thank you!

**Comment by sayloo** [comment]
This is because of the "Transposh" (Language Translation)  plugin which is basically trying to translate the image along with the text. I am not sure if we can avoid this.
If possible, I'll try to come up with a decent workaround.

**Comment by cassininazir** [comment]
We may not be able to fully fix. One workaround to the not being able to scroll issue:

Hit Cmd (or Control on Windows) + F and do a search for the word �Publish�; usually pulls you back to the top of the page and allows you to save the document or as a drafty.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#185
