### ISSUE TITLE
Anthropodcast Channel Setup

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#57]
@yvantina let us know that we are expecting a new podcast from Switzerland. Have not received forms as of yet.

**Comment by yvantina** [comment]
@Cassini
** A new Channel to be more precise - they will filled the forms as soon as
possible !
thanks !

yvan

2015-03-09 14:21 GMT-06:00 Cassini Nazir <notifications@github.com>:

> @yvantina <https://github.com/yvantina> let us know that we are expecting
> a new podcast from Switzerland. Have not received forms as of yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/public-website/issues/57>.
>



-- 
check out this website for more information on art, synthetic biology and
a-life
http://synthbioart.texashats.org/

**Comment by cassininazir** [comment]
@yvantina any update on the Anthropodcast? May have missed an email about this.

**Comment by yvantina** [comment]
@rmalina @cassininazir  I sent him a reminder few days ago, given he said he would get the forms filled about two months ago... but Jonathan never followed up with tangible actions ! so..still waiting...

**Comment by cassininazir** [comment]
Unassigning Vivek from this task. Leaving this open in case the channel forms.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#184
