### ISSUE TITLE
Facebook Post Metadata

### ISSUE THREAD

**Issue by vivraman** [creativedisturbance/public-website#58]
Voices/Channels/Podcasts posted to Facebook have various issues relating to thumbnail and caption metadata. Look into potential solutions.

**Comment by vivraman** [comment]
Check this out: http://stackoverflow.com/questions/9505327/what-graphic-does-fb-grab

**Comment by cassininazir** [comment]
Good find. Vivek, could you try to implement this using PHP? Pretty straightforward fix to edit the <head> tag. 

@anvit should have the production server up (on Heroku), see the password document for information.

**Comment by cassininazir** [comment]
@anvit has implemented this recently.
