### ISSUE TITLE
Install a WordPress Theme for Experimental Space and Post a Sample Experiment

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#6]
_From @cassininazir on February 18, 2015 21:3_

_Copied from original issue: cassininazir/creativedisturbance#109_

**Comment by cassininazir** [comment]
@vivraman Add a link here to the theme you mentioned. Get input from podcast team and Scot GL. Will then purchase.

**Comment by vivraman** [comment]
We are currently past this stage
