### ISSUE TITLE
Change textinput for Channel Names to  dropdown in WordPress 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#64]
This will make the job of the podcast team easier and prevent issues with name changes.

Also describe how admins can add a new channel.

**Comment by anvit** [comment]
Add drop down in https://cd-autopost.herokuapp.com instead of Wordpress

**Comment by cassininazir** [comment]
Closing this issue. Once the auto poster is created this will be a non-issue.
