### ISSUE TITLE
Add Stingers to Experimental Space

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#69]
Sound team will be working on podcast that explains their stingers.

**Comment by cassininazir** [comment]
- Remove "Check back often for more content!" 
- Explain what are stingers ??? 
- Add names of people who created. 
- Change background of SoundCloud - talk to @heiwanalady if a new graphic image is needed. Give her enough lead time.
- Talk to @porteriffic, @coreysmart92 about timeline for stingers. We can add new stingers as they become available. 
- If you like, ask @linamoon to stage a photo of sound team for inclusion in this. Would need something like this for the blog.

**Comment by vivraman** [comment]
![20150409_171318](https://cloud.githubusercontent.com/assets/8704629/7078177/638c8a16-dedc-11e4-9b8b-9c402247f8c0.jpg)

**Comment by vivraman** [comment]
@cassininazir http://propodder.com/2011/05/bumpers-sweepers-stingers-and-drops/

maybe we should consider changing the terminology we use, instead of stinger use something else? let me know what you think

**Comment by cassininazir** [comment]
Run this by the @creativedisturbance/sound team.
