### ISSUE TITLE
Meet the Team Page - Updates

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#7]
_From @heiwanalady on February 13, 2015 18:39_

Need to add Josephine, Corey, and Ashton.
I have asked them to send me or Vivek their short bios. (Stephanie can help with this)

Also need to set up a "Former Student / Lab Interns" (put Stephen Witt in there - as he no longer works for us). 

_Copied from original issue: cassininazir/creativedisturbance#104_

**Comment by cassininazir** [comment]
Received Josey's. Waiting for the Hal, Ashton and Corey.

**Comment by cassininazir** [comment]
_From @vivraman on February 16, 2015 18:14_

Also would like to include CD Alumni (don't need their photos):

Cathryn Ploehn
http://creativedisturbance.org/meet-the-team/

**Comment by vivraman** [comment]
Done. http://creativedisturbance.org/meet-the-team/

**Comment by cassininazir** [comment]
This looks great. A few minor changes:

- Make Cathryn Ploehn's name a link to her website at http://cathrynploehn.com/ 
- Will need to add Chaz Lilly to the list as well

**Comment by vivraman** [comment]
Done as well.
