### ISSUE TITLE
Document process for moving live website updates to production

### ISSUE THREAD

**Issue by anvit** [creativedisturbance/public-website#72]
Make a Google Doc with detailed steps about moving the live website(database) changes to production migrating the production development changes to the live website.

**Comment by anvit** [comment]
Done. File: Google docs>4.0 Reference Docs>How to update production and live servers

**Comment by cassininazir** [comment]
Bellissimo!
________________________________

**Comment by cassininazir** [comment]
Have labeled this doc as 4.2.
