### ISSUE TITLE
Add list of individuals from Kickstarter page to About Us page

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#75]
The "founders" - list of ~100 people

**Comment by cassininazir** [comment]
@heiwanalady could you give us the appropriate list?

**Comment by heiwanalady** [comment]
@cassininazir 
Here is the list of Founders (they pledged $20+):

Steven Joscherwitz
Diane Burko
Amy Ho
nina yankowitz
Lindsey Joyce
Christine Bernier
prithvi (no last name available)
Chris Welch
Jose-Carlos Mariategui
Rob La Frenais
Greta Poulsen
Susan Eriksson
Steve DiPaola
Arthur Woods
Richard Clar
Syeda Sarosh Ahmed
Christian La Mont
John Bell
Tiffany Shlain
Mert Iseri
Serge Ruffato
Diane Gromala
Czarina Cando
Chelsea Maxwell
Corey Smart
Charles Lindsay
Anna Dumitriu
Lorella Abenavoli
Edward Shanken
chris coleman
TINA Blanche
Michael Sherrod
Prof. Dr. JIll Scott
Fernando Sapiña
marc hebert
Guillermo Muñoz
Simon Perez Wilson
Earl Powell
Marcelle Rhoda Finyom
Gladys Finyom
Tina Anna
Tasnim Benhalim
Stephanie Brisendine
Annick Bureaud
Cassini Nazir
ruth catchen
amal alayan
Santosh Shettar
Karen Doore
Meredith Tromble
Rebekah K Nix
Sarah Jane Pell
John Vallerga
Stephen Witt
Brian Jones
Hervé FISCHER
Craig Harris
Cid Nazir
Sarah Larson
Antonio Smith
Ingrid Kepinski
Carol LaFayette
Morgan O'Hara
Natan Karczmar
Darlene Tong
Lavanya Camsaripalli
Nigel Nazir
Maximilian Schich
Jean-Luc Soret
michael naimark
Amanda Sparling
Cathryn Ploehn
Tania Hershman
Alexander M Djerassi
Shruthi Ayloo
Anvit Srivastav
Kyle Kondas
Nisar Keshvani
Wolf RAINER
Scot Gresham-Lancaster
Jack Ox
Gagan Wig
X to the M (The email is xmalina@gmail.com = Mailna family)
Alan Malina
Max M (no last name available)
Carol Strohecker
Paul Fishwick
Lucinda Presley
Lucy Petrovic
Yuri Frank Maxwell Malina
yvonne meynard
Isabel Maxwell
Vic Simon
Mumonkan (Jon Van Oast)
Arun Augustine
Wendi Kavanaugh
Alisa Nazir
Yvan Tina
David Marlett


The following people did not chose an award/perk level, so I'm not sure if we should put them on the website for courtesy or not.

Sarah McAndrews (top donator - $1,500)
Robert Thill
Wendy Silk
Wm Fawley
Liliane Lijn
Linda Henderson
Samuel Okoshken
Christiane Paul
Karen O'Rourke
Andrew Blanton
Martine Epoque
MaryEllen Lacy
