### ISSUE TITLE
Remove Recording Date from WordPress Podcasts as a required field 

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#76]
Remove entirely

**Comment by cassininazir** [comment]
What is highlighted in the image below is the recording date (which is manually put in to WordPress). Please:

1. Replace with date published in WordPress 
2. And then remove as required field from Podcast Submission Page

![screen shot 2015-03-30 at 11 47 40 am](https://cloud.githubusercontent.com/assets/1661430/6901411/980f80f2-d6d2-11e4-9903-664ad6acdbcb.png)

**Comment by anvit** [comment]
Removed recording date from podcasts. The podcasts will now automatically display the published date.
