### ISSUE TITLE
chrome compatibility

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#79]
on line form doesnt work in chrome-make sure new form works on all browsers

**Comment by cassininazir** [comment]
Will do testing to review this. Was this on your computer or reported from a producer/guest? Would like to reproduce the problem if possible.

**Comment by rmalina** [comment]
on my computer
roger

On Mon, Mar 30, 2015 at 9:35 AM, Cassini Nazir <notifications@github.com>
wrote:

> Will do testing to review this. Was this on your computer or reported from
> a producer/guest? Would like to reproduce the problem if possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativedisturbance/public-website/issues/79#issuecomment-87703923>
> .
>



-- 
Roger F Malina
is in texas
1-510-853-2007

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#180
