### ISSUE TITLE
Create new channel for Cellphonia

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#8]
_From @cassininazir on January 30, 2015 18:34_

When Stephanie completes the album artwork, please create the Channel for this. Work with sound team on when this will go out. 

_Copied from original issue: cassininazir/creativedisturbance#70_

**Comment by cassininazir** [comment]
_From @vivraman on February 9, 2015 17:45_

Channel is ready to go up except artwork, waiting for Stephanie to get back to me so I can add that.

**Comment by cassininazir** [comment]
From convo with Scot:

- Will have podcasts with the experimenters discussing content (this will actually go into the Sound and Data channel)
- Will also need to have the Experimental space go up at the same time that the podcast goes up

**Comment by cassininazir** [comment]
@heiwanalady's artwork is being finalized. Don't publish until we have first podcast.

**Comment by vivraman** [comment]
Artwork is up. Channel is ready to publish as soon as we have a podcast for it.

**Comment by cassininazir** [comment]
This looks great. A few minor changes:

- Make Cathryn Ploehn's name a link to her website at http://cathrynploehn.com/ 
- Will need to add Chaz Lilly to the list as well

**Comment by vivraman** [comment]
Changes made.
