### ISSUE TITLE
Add Marcus Neustetter to Meet the Team Page

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#85]
Talk to Roger about his role.

Marcus is setting up a community radio station in Johannesburg as well.

**Comment by porteriffic** [comment]
I've started a draft for him. I was wondering if we need to give him a different bio by stating his involvement with Creative Disturbance and UTD.

**Comment by porteriffic** [comment]
Okay turns out I can't save him as a draft. He's on the Meet the Team page but I will need to update his bio a little bit this week.
