### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/public-website#86]
Scot says you can't subscribe to a specific channel on website. I think it's the issue we talked about a couple weeks ago about Libsyn. There's no meta data and stuff...

**Comment by cassininazir** [comment]
@anvit discovered this is possible. Use 

http://createdisturb.libsyn.com/feed/category/**Category%20Title**

Where **Category%20Title** is the name of the channel with **%20** instead of spaces.
