### ISSUE TITLE
wrong podcast with description

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#89]
http://creativedisturbance.org/podcast/the-johannesburg-rocket-factory-2/

this podcast has the wrong description

check wiht yvan tina

roger

**Comment by cassininazir** [comment]
Discussed at the team meeting today. @creativedisturbance/sound, @coreysmart92, is looking into this.

**Comment by cassininazir** [comment]
@porteriffic fixed this. Thank you.
