### ISSUE TITLE
Album Artwork for Noisy People

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#90]
Some artwork available here for possible use: 

 - http://www.noisypeople.perkis.com/epk.html

**Comment by cassininazir** [comment]
Just received the form description.

**Comment by heiwanalady** [comment]
Ok, I have the logo. Just need to communicate with Tim to see if he wants anything specific on the artwork - if not I'll take artistic liberty.

**Comment by cassininazir** [comment]
Closing this out. The artwork is now live.
