### ISSUE TITLE
RSS Feed for Specific Channels

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/public-website#91]
Try to do this in LibSyn. Benefits us because we can push to iTunes. 

We need feeds for both individual channels and all Creative Disturbance podcasts.

**Comment by cassininazir** [comment]
I explored LibSyn. This does not appear to be possible. Please instead create a script that generates the specific feed.

**Comment by anvit** [comment]
Found a simple hack, Just add ?category='category name' to the end of the feed URL. For e.g.
http://createdisturb.libsyn.com/feed?category=Meta-Life
(works with spaces too!)
http://createdisturb.libsyn.com/feed?category=Indie Game Nation
http://createdisturb.libsyn.com/feed/?category=Noisy People
