### ISSUE TITLE
Podcast covers on Facebook

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#92]
Automatic plugin issue on Facebook :
Podcasts are posted with the same cover (space art&culture) since 3 months, reducing significantly our attractiveness .. so can we fix it or assign someone from the production team to manually post each podcast with the right information ?

**Comment by cassininazir** [comment]
Add the Ultimate Facebook plugin to the production server. Create a dummy Facebook page (or you may use your own!) and test this out. 

- Use the OpenGraph image textfield to specify the image to be used.
- Setup to autopost to Facebook.

**Comment by cassininazir** [comment]
The OpenGraph image should solve the problem we are experiencing where every podcast has the same image when posted to Facebook. In the image below, none of the album artwork is correct. 

![screen shot 2015-04-21 at 1 19 44 pm](https://cloud.githubusercontent.com/assets/1661430/7259469/1a3431ba-e829-11e4-8ca7-f3a69dd64ba9.png)

**Comment by cassininazir** [comment]
Update: simplest fix is to edit the PHP template to add the follow meta information in the <head> tag:

< meta property="og:image"
content="http://graphics.myfavnews.com/images/logo-100x100.jpg" /> 

Where the content is the URL of the specific podcast. This way we don't have to use Facebook plugin. 

![screen shot 2015-04-21 at 3 10 26 pm](https://cloud.githubusercontent.com/assets/1661430/7261582/935bf5aa-e838-11e4-837c-648700641af5.png)

**Comment by cassininazir** [comment]
A good write-up from David Walsh on Open Graph properties. 

http://davidwalsh.name/facebook-meta-tags

**Comment by anvit** [comment]
I've gone and added the meta tags as per the open graph properties but there isn't a way to test it out unless it starts actually posting to a facebook page. Should we enable the Ultimate facebook plugin before the next podcast goes up and see if it works?

**Comment by cassininazir** [comment]
Yes! Please, test this out before unleashing upon the world.

Also confirm that the Facebook plugin does not throw any errors or exceptions on the live website.

This will help in our Community Building.

Cassini Nazir

Clinical Assistant Professor,
School of Arts and Technology and Emerging Communication
The University of Texas at Dallas

**Comment by anvit** [comment]
Done setting up meta tags for facebook. Will enable the plugin tonight before the podcast goes live to see if it works.

**Comment by anvit** [comment]
Facebook doesn't seem to be picking up the meta tags when auto posting using Ultimate Facebook. Also, Facebook doesn't detect og:image at all. Need to investigate

**Comment by anvit** [comment]
Enabling Ultimate facebook temporarily. Testing out some open graph meta tags with the Dhameen Ansari podcast

**Comment by anvit** [comment]
The FB auto post plugin doesn't seem to be working correctly. Attempted correcting the podcast covers with both - script generated open graph meta tags and the meta tags from the plugin sidebar.

**Comment by anvit** [comment]
Fixed the open graph meta tags. Facebook should automatically grab the correct image while posting now.
