### ISSUE TITLE
error message when i try to go on the cd web site

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/public-website#93]
i get this error message when i go to the CD web site

Warning: session_start() [function.session-start]: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /home4/atec/public_html/cd/wp-content/plugins/wpmu-dev-facebook/lib/external/facebook.php on line 60

roger

**Comment by cassininazir** [comment]
I�m disabling this plug-in until we can get to the bottom of it. It seems to have disabled the error message.

Cassini Nazir

Clinical Assistant Professor, Arts and Technology
The University of Texas at Dallas

**Comment by cassininazir** [comment]
@anvit assigning this to you. I turned off the plugin to make sure this error doesn't appear. See if you can re-produce on the production server. 

Also, I think this plugin is different from the one we are actually using. Please investigate, and if we are not using this plugin from WPMU, remove from live server.

**Comment by cassininazir** [comment]
This has been resolved. No longer using hte WPMU plugin.
