### ISSUE TITLE
Aziz Mohamed description

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/public-website#96]
hey Hal
I've found that the current title and description of "Faire palpiter les sens et retrouver l'intemporel" with Aziz Mohamed doesn't fit with the podcast's content..
can you please find the right podcast info form and use the current title and description for the second part of our discussion which is the other podcast I've done with Chafchaouni..

Again this podcast 
http://creativedisturbance.org/podcast/faire-palpiter-les-sens-et-retrouver-lintemporel/
should be entitled "Appel à contributions pour un laboratoire d’idées" 
and his description should be 
"Dans la première partie de cet entretien, Mohamed Aziz Chafchaouni tente de répondre à la question “Qu’est-ce que Afrique Virtuelle ?” au regard des phénomènes de mondialisation et des possibilités offertes par les techno-sciences. Après avoir discuté, entre autres, des enjeux de démocratisation du savoir et d’une nécessaire réappropriation de l’outil technologique, Mohamed A. Chafchaouni propose de réfléchir à la création d’un “think tank” pluridisciplinaire qui oeuvre à la formulation conceptuelle et théorique du projet."

keywords are : démocratisation, visibilité, esthétique, T.I.C, think thank

Much thanks !!

**Comment by cassininazir** [comment]
@halclark please close if this is taken care of.

**Comment by halclark** [comment]
updated title and description, forgot to close.
